version: "3.8"
services:
    bot:
        image: nacknime/gdz_ukraine_bot:latest
        build: .
        restart: on-failure
        stop_signal: SIGINT
        depends_on:
            postgres:
                condition: service_healthy
            mongo:
                condition: service_started
        env_file: .env
        environment:
            POSTGRES_HOST: postgres
            POSTGRES_PORT: "${POSTGRES_PORT}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DB: "${POSTGRES_DB}"
            MONGO_HOST: mongo
            MONGO_PORT: "${MONGO_PORT}"

    mongo:
        image: mongo:4.4.6
        restart: on-failure
        volumes:
            - mongo-data:/data

    postgres:
        image: postgres:12-alpine
        restart: on-failure
        volumes:
            - postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
            interval: 1s
            timeout: 5s
            retries: 5
        environment:
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_DB: "${POSTGRES_DB}"

volumes:
    mongo-data:
    postgres-data:
