"""add year column

Revision ID: 06d87926c931
Revises: 67170eb02e22
Create Date: 2020-05-18 16:40:29.988883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d87926c931'
down_revision = '67170eb02e22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'year')
    # ### end Alembic commands ###
