"""add is_blocked column

Revision ID: 2086ea435549
Revises: efa23160c50b
Create Date: 2020-06-07 10:51:24.383788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2086ea435549'
down_revision = 'efa23160c50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###
