"""add exercise column

Revision ID: 379ae812db73
Revises: d2530e528c53
Create Date: 2020-05-20 11:44:27.814052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '379ae812db73'
down_revision = 'd2530e528c53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('exercise', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'exercise')
    # ### end Alembic commands ###
