"""add_timers

Revision ID: 746a1d372012
Revises: fd5e49a12374
Create Date: 2020-03-29 17:24:53.810328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746a1d372012'
down_revision = 'fd5e49a12374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    # ### end Alembic commands ###
