"""created Solution model for many-to-one ref

Revision ID: d4197879130e
Revises: 2086ea435549
Create Date: 2020-10-10 21:56:01.235276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4197879130e'
down_revision = '2086ea435549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('solutions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solutions_id'), 'solutions', ['id'], unique=True)
    op.add_column('photos', sa.Column('solution_id', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('url', sa.String(), nullable=True))
    op.alter_column('photos', 'photo_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_foreign_key('photos_solution_id_fkey', 'photos', 'solutions', ['solution_id'], ['id'])

    # my code goes here
    op.execute("insert into solutions (id) select id from photos;")
    op.execute("update photos set solution_id = id;")
    op.drop_column("photos", "id")
    # op.drop_index(op.f('ix_photos_id'), table_name='photos')
    op.execute("alter table photos add column id serial primary key;")
    op.create_index(op.f('ix_photos_id'), 'photos', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # my code goes here
    op.execute("update photos set id = solution_id;")
    # my code ends

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('photos_solution_id_fkey', 'photos', type_='foreignkey')
    op.alter_column('photos', 'photo_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('photos', 'url')
    op.drop_column('photos', 'solution_id')
    op.drop_index(op.f('ix_solutions_id'), table_name='solutions')
    op.drop_table('solutions')
    # ### end Alembic commands ###
