"""Added is_subscribed_to_notifications on User table

Revision ID: e867d8d5dcde
Revises: d4197879130e
Create Date: 2021-04-01 09:41:01.561649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e867d8d5dcde'
down_revision = 'd4197879130e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_subscribed_to_notifications', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET is_subscribed_to_notifications = true")
    op.alter_column('users', 'is_subscribed_to_notifications', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_subscribed_to_notifications')
    # ### end Alembic commands ###
