"""init

Revision ID: fd5e49a12374
Revises: ebd87de4edcc
Create Date: 2020-03-28 16:27:29.363569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5e49a12374'
down_revision = 'ebd87de4edcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
